import type {CustomizationCardData} from '@/components/customization/customization-card';

export const CUSTOMIZATION_CATEGORIES: CustomizationCardData[] = [
    {
        _id: 'mock-customization-metallic-paperboard',
        title: 'Metallic Paperboard',
        slug: 'metallic-paperboard',
        categoryValue: 'material',
        categoryLabel: 'Material',
        imageUrl: null,
        imageAlt: 'Metallic Paperboard',
    },
    {
        _id: 'mock-customization-sbs-paperboard',
        title: 'SBS Paperboard',
        slug: 'sbs-paperboard',
        categoryValue: 'material',
        categoryLabel: 'Material',
        imageUrl: null,
        imageAlt: 'SBS Paperboard',
    },
    {
        _id: 'mock-customization-kraft-paper',
        title: 'Kraft Paper',
        slug: 'kraft-paper',
        categoryValue: 'material',
        categoryLabel: 'Material',
        imageUrl: null,
        imageAlt: 'Kraft Paper',
    },
    {
        _id: 'mock-customization-matte-lamination',
        title: 'Matte Lamination',
        slug: 'matte-lamination',
        categoryValue: 'finish',
        categoryLabel: 'Finish',
        imageUrl: null,
        imageAlt: 'Matte Lamination',
    },
    {
        _id: 'mock-customization-soft-touch-coating',
        title: 'Soft-Touch Coating',
        slug: 'soft-touch-coating',
        categoryValue: 'finish',
        categoryLabel: 'Finish',
        imageUrl: null,
        imageAlt: 'Soft-Touch Coating',
    },
    {
        _id: 'mock-customization-foil-stamping',
        title: 'Foil Stamping',
        slug: 'foil-stamping',
        categoryValue: 'finish',
        categoryLabel: 'Finish',
        imageUrl: null,
        imageAlt: 'Foil Stamping',
    },
];
