export type {
    BuilderCardinality,
    BuilderChoice,
    BuilderMode,
    BuilderOption,
    BuilderStep,
    BuilderStepKey,
    BuilderType,
    CatalogOptionLike,
    CustomizationBuilderState,
    DimensionFace,
    DimensionsValue,
    FaceMeasurements,
    PrintSideValue,
    SelectionValue,
    StepAnswer,
    PropertySelectionSummaryItem,
} from '@/lib/customization-builder/types';

export {
    answerSelections,
    buildStepsFromCatalog,
    createEmptyBuilderState,
    emptyDimensions,
    emptyFace,
    fillUnsetWithConsultation,
    formatDimensionsSummary,
    formatFaceSummary,
    formatPrintedSideSummary,
    getAnswer,
    getDimensionsValue,
    isAnswerReady,
    isPrintedSideComplete,
    isPrintingCategoryStep,
    isPrintingStepReady,
    isStepReady,
    firstUnresolvedStepIndex,
    isBuilderConfigured,
    isBuilderReady,
    markGuidedComplete,
    optionsForType,
    parseBuilderState,
    patchAnswer,
    patchPrintedSide,
    clearStep,
    patchEntryNote,
    patchFace,
    patchPropertySelections,
    removeSelections,
    seedFromCustomizations,
    shouldEnterGuided,
    summarizeAnswer,
    summarizePrintingStep,
    summarizeSelection,
    toggleSelection,
    visiblePropertySummaries,
    wantsAnyPrint,
    selectPrintingConsultation,
    toRequestCustomizations,
    type BuilderRequestCustomization,
    type PropertySummariesByOption,
} from '@/lib/customization-builder/state';

export {
    DIMENSIONS_STEP_KEY,
    DIMENSION_FACES,
    EMPTY_BUILDER_STATE,
    EMPTY_DIMENSIONS,
    EMPTY_FACE,
    PRINTING_CATEGORY_SLUG,
    dimensionEntryNoteKey,
} from '@/lib/customization-builder/types';
