export type {
    BuilderChoice,
    BuilderMode,
    BuilderOption,
    BuilderStep,
    BuilderStepKey,
    BuilderType,
    CatalogOptionLike,
    CustomizationBuilderState,
    DimensionFace,
    DimensionsValue,
    FaceMeasurements,
    SelectionValue,
    StepAnswer,
} from '@/lib/customization-builder/types';

export {
    buildStepsFromCatalog,
    createEmptyBuilderState,
    emptyDimensions,
    emptyFace,
    fillUnsetWithConsultation,
    formatDimensionsSummary,
    formatFaceSummary,
    getAnswer,
    getDimensionsValue,
    isAnswerReady,
    firstUnresolvedStepIndex,
    isBuilderConfigured,
    isBuilderReady,
    markGuidedComplete,
    optionsForType,
    parseBuilderState,
    patchAnswer,
    clearStep,
    patchEntryNote,
    patchFace,
    seedFromCustomizations,
    shouldEnterGuided,
    summarizeAnswer,
    toRequestCustomizations,
    type BuilderRequestCustomization,
} from '@/lib/customization-builder/state';

export {
    DIMENSIONS_STEP_KEY,
    DIMENSION_FACES,
    EMPTY_BUILDER_STATE,
    EMPTY_DIMENSIONS,
    EMPTY_FACE,
    dimensionEntryNoteKey,
} from '@/lib/customization-builder/types';
