export const ADMIN_REQUESTS_COPY = {
  listTitle: "Requests",
  emptyList: "No requests yet.",
  breadcrumbRequests: "Requests",
  editAction: "Edit",
  comingSoon: "Coming Soon",
  statusSubmitted: "Submitted",
  entryKindExpress: "Express",
  entryKindProducts: "Products",
  entryKindServices: "Services",
  detailMetaFromCompany: (company: string) => `from ${company}`,
  sectionContact: "Contact",
  sectionRequirements: "Requirements",
  sectionProductLines: "Products",
  sectionTimeline: "Timeline",
  sectionArtwork: "Additional Files",
  sectionServices: "Services",
  emptyProductLines: "No products on this request.",
  emptyArtwork: "No files attached.",
  attachmentView: "View",
  attachmentOpen: "Open",
  attachmentDownload: "Download",
  attachmentClose: "Close",
  attachmentOpening: "Opening…",
  attachmentError: "Could not open that file.",
  emptyServices: "No services selected.",
  emptyValue: "—",
  submittedLabel: "Submitted",
  entryKindLabel: "Entry type",
  requirementTypeLabel: "Requirement Type",
  packagingContentsLabel: "Packaging contents",
  briefLabel: "Brief",
  timelineLabel: "Timeframe",
  shipToLabel: "Ship to",
  nameLabel: "Name",
  emailLabel: "Email",
  /** The ACCOUNT that submitted it — not necessarily the contact address above. */
  submittedByLabel: "Submitted by (account)",
  accountGuest: "Guest — no account",
  /** `customer_id` is set but the customer row did not come back: the lookup
   *  failed, or `customers_select_assigned_internal` did not admit it (which is
   *  what happens while the lead is unassigned). */
  accountUnresolved: "Registered — account not visible",
  phoneLabel: "Phone",
  companyLabel: "Company",
  industryLabel: "Industry",
  annualSpendLabel: "Annual spend",
  quantitiesLabel: "Quantities",
  customizationsLabel: "Customizations",
  productSlugLabel: "Product",
  unitsSuffix: "units",
  contentsLabel: "Packaging contents",
  notesLabel: "Notes",
  customizeLine: "Customize",
  notesAndImagesAction: "Notes & images",
  removeLine: "Remove",
  addMoreProducts: "Add another product",
  timelineCommentPlaceholder: "Leave a comment...",
  timelineCommentFuture: "Future feature",
  timelinePost: "Post",
  timelineStaffOnly: "Only you and other staff can see comments.",
  timelineEmpty: "No activity yet.",
  timelineVersionLabel: (n: number) => `Version ${n}`,
  paperPagesNav: "Document pages",
  paperPageLabel: (page: number, total: number) => `Page ${page} of ${total}`,
} as const;
