export const CUSTOMIZATION_BUILDER_COPY = {
    title: 'Customize your packaging',
    guidedIntro:
        'Answer one step at a time — or choose “Need consultation” and a specialist will advise.',
    workspaceIntro:
        'Review or change any option. Everything stays editable.',
    stepOf: 'Step {current} of {total}',
    back: 'Back',
    next: 'Next',
    skipNotSure: 'Need consultation',
    notSureHelper: 'We’ll keep this Ready — a specialist will advise.',
    specialistToAdvise: 'Specialist to advise',
    notSet: 'Not set',
    ready: 'Ready',
    close: 'Close',
    save: 'Save',
    length: 'Length',
    width: 'Width',
    height: 'Height',
    unit: 'Unit',
    unitIn: 'in',
    unitMm: 'mm',
    selectOption: 'Select an option',
    navLabel: 'Customization categories',
    typeListLabel: 'Category types',
    detailLabel: 'Detail',
    external: 'External',
    internal: 'Internal',
    measurements: 'Measurements',
    pickAnOption: 'Choose an option for this type.',
    chooseOne: 'Choose one',
    chooseAny: 'Choose any',
    unavailableWithSelections: 'Not available with your current selections',
    additionalNote: 'Additional note',
    addAdditionalNote: '+ Additional Note',
    removeSelection: 'Remove selection',
    additionalNotePlaceholder:
        'Specific {category} details for your specialist…',
    skip: 'Skip, need consultation',
    /** PROD-2629 / ADR-017 — reverse of Sanity `achieves` (candidates, not a recipe). */
    achievedByHelper:
        'This finish can be achieved by these techniques, learn more about them:',
    achievedBySelected: 'Technique',
    achievedByLearnMore: 'Learn more',
    /** Printing-step Printed Side gate (before Method / Color). */
    printOutside: 'Print Outside',
    printInside: 'Print Inside',
    printedSideYes: 'Yes',
    printedSideNo: 'No',
    /** Pantone Spot / Hybrid option detail controllers. */
    pantoneCountLabel: 'How many Pantone colors?',
    pantoneCountDecrease: 'Fewer Pantone colors',
    pantoneCountIncrease: 'More Pantone colors',
    pantonePmsLabel: 'Pantone (PMS) codes',
    pantonePmsPlaceholder: 'e.g. PMS 185 C',
    pantonePmsRemove: 'Remove Pantone code',
} as const;
