export const CUSTOMIZATION_BUILDER_COPY = {
    title: 'Customize your packaging',
    guidedIntro:
        'Answer one step at a time — or choose “Need consultation” and a specialist will advise.',
    workspaceIntro:
        'Review or change any option. Everything stays editable.',
    guidedFinished:
        'You’re set — tweak anything below, or close when you’re ready.',
    stepOf: 'Step {current} of {total}',
    back: 'Back',
    next: 'Next',
    done: 'Done',
    skipNotSure: 'Need consultation',
    notSureHelper: 'We’ll keep this Ready — a specialist will advise.',
    specialistToAdvise: 'Specialist to advise',
    notSet: 'Not set',
    ready: 'Ready',
    close: 'Close',
    save: 'Save',
    length: 'Length',
    width: 'Width',
    height: 'Height',
    unit: 'Unit',
    unitIn: 'in',
    unitMm: 'mm',
    selectOption: 'Select an option',
    navLabel: 'Customization categories',
    typeListLabel: 'Category types',
    detailLabel: 'Detail',
    external: 'External',
    internal: 'Internal',
    measurements: 'Measurements',
    pickAnOption: 'Choose an option for this type.',
    additionalNote: 'Additional note',
    addAdditionalNote: '+ Additional Note',
    removeSelection: 'Remove selection',
    additionalNotePlaceholder:
        'Specific {category} details for your specialist…',
    skip: 'Skip, need consultation',
} as const;
