export const ACCOUNT_COPY = {
    signOut: 'Sign out',
    requestsTitle: 'Requests',
    requestsEmpty:
        'You have not submitted any requests yet. Start a request to get a quote from our packaging specialists.',
    startARequest: 'Start a request',
    profileTitle: 'Profile',
    contactTitle: 'Contact',
    companyAddressTitle: 'Company address',
    addressesTitle: 'Addresses',
    marketingTitle: 'Marketing preferences',
    edit: 'Edit',
    done: 'Done',
    add: 'Add',
    cancel: 'Cancel',
    save: 'Save',
    addAddressTitle: 'Add address',
    editContactTitle: 'Edit contact',
    editCompanyAddressTitle: 'Edit company address',
    fieldName: 'Name',
    fieldEmail: 'Email',
    fieldPhone: 'Phone',
    fieldCompany: 'Company',
    fieldIndustry: 'Industry',
    fieldLine1: 'Address line 1',
    fieldLine2: 'Address line 2',
    fieldCity: 'City',
    fieldRegion: 'State / province',
    fieldPostal: 'Postal code',
    fieldCountry: 'Country',
    noCompanyAddress: 'No company address added',
    noAddresses: 'No addresses added',
    defaultLabel: 'Default',
    marketingEmailAria: 'Email marketing preferences',
} as const;
