export const ACCOUNT_COPY = {
    signOut: 'Sign out',
    welcomeBack: 'Welcome back,',
    accountMenu: 'Account menu',
    requestsTitle: 'Your Requests',
    requestsEmpty:
        'You have not submitted any requests yet. Start a quote request to get a quote from our packaging specialists.',
    startARequest: 'Start a quote request',
    backToRequests: '← Your requests',
    questionsAboutRequest: 'Questions about this request?',
    emailYourTeam: 'Email your Project Specialist',
    quotesEmail: 'quotes@pakfactory.com',
    submittedOn: (date: string) => `Submitted ${date}`,
    /** Display-only until real RFQ statuses ship; DB is still only `submitted`. */
    statusPending: 'Pending',
    itemsHeading: 'Items',
    filesHeading: 'Files you attached',
    briefNotSet: 'Not set',
    briefHeading: 'Brief',
    shipToHeading: 'The product will be shipped to',
    servicesSelectedHeading: 'Additional services',
    /** Named "Contact email", not "Your email": for a request raised on a
     *  colleague's behalf it is deliberately not the reader's own address. */
    fieldContactEmail: 'Contact email',
    fieldContents: 'Contents',
    fieldQuantity: 'Quantity',
    fieldTimeline: 'Timeline',
    fieldShipTo: 'Ship to',
    fieldNotes: 'Notes',
    fieldCustomizations: 'Customizations',
    fieldCountry: 'Country',
    fieldAddress: 'Address',
    fieldApartment: 'Apartment, suite, etc.',
    fieldCity: 'City',
    fieldRegion: 'State / province',
    fieldPostal: 'Postal code',
    profileTitle: 'Profile',
    contactTitle: 'Contact',
    companyAddressTitle: 'Company address',
    addressesTitle: 'Addresses',
    marketingTitle: 'Marketing preferences',
    passwordTitle: 'Password',
    resetPassword: 'Reset password',
    resetPasswordDescription: 'Send a reset link to your email',
    edit: 'Edit',
    done: 'Done',
    add: 'Add',
    cancel: 'Cancel',
    save: 'Save',
    addAddressTitle: 'Add address',
    editContactTitle: 'Edit contact',
    editCompanyAddressTitle: 'Edit company address',
    fieldName: 'Name',
    fieldEmail: 'Email',
    fieldPhone: 'Phone',
    fieldCompany: 'Company',
    fieldIndustry: 'Industry',
    fieldLine1: 'Address line 1',
    fieldLine2: 'Address line 2',
    noCompanyAddress: 'No company address added',
    noAddresses: 'No addresses added',
    defaultLabel: 'Default',
    marketingEmailAria: 'Email marketing preferences',
} as const;
