export const REQUEST_COPY = {
    addToRequest: 'Add to request',
    addedToYourRequest: 'Added to your request',
    viewYourRequest: 'View your request',
    contentsLabel: 'What are you putting in the packaging?',
    contentsHelp: 'The product that goes inside — bottles, jars, kits…',
    contentsPlaceholder: 'e.g. 750ml spirit bottles, skincare jars…',
    additionalNotesOrImages: 'Additional notes or images for this product?',
    additionalNotesLabel: 'Additional notes',
    additionalNotesPlaceholder:
        'Fit, brand cues, or anything specific to this structure…',
    addImagesLabel: 'Add images',
    optional: '(optional)',
    no: 'No',
    yes: 'Yes',
    customizationHeading: 'Customization',
    specialistCanPropose:
        'A specialist can propose materials and finishes with your request.',
    customizeItYourself: 'Customize it yourself',

    // BriefBuilder / wizard
    railHeading: 'The more you share, the faster we can quote.',
    needHelpPrefix: 'Need help?',
    startChat: 'Start chat',
    yourRefPrefix: 'Your ref# is',
    refPlaceholder: 'RFQ-#####',
    close: 'Close',
    saveDraft: 'Save draft',

    productsTitle: 'Products',
    productsSubtitle: 'Add items',
    servicesTitle: 'Services',
    servicesSubtitle: 'Extras',
    servicesHeading: 'Services',
    servicesDesc: '',
    requirementsTitle: 'Your Requirements',
    requirementsSubtitle: '',
    yourInformationTitle: 'Your Information',
    yourInformationSubtitle: '',
    reviewTitle: 'Review your request',
    reviewSubtitle:
        'One last look — then a specialist will quote pricing, lead time, and next steps.',
    letterheadName: 'PakFactory',
    letterheadTagline: 'Custom packaging quotes',
    preparedFor: 'Prepared for',
    shippedToAddress: 'Shipped to Address',
    paperEdit: 'Edit',
    paperBrief: 'Brief',
    paperQty: 'Qty',
    paperItem: 'Item',
    paperConfiguration: 'Configuration',
    noProductsAdded: 'No products added.',
    regionToConfirm: 'Region — to confirm',
    notSet: 'Not set',
    paperDisclaimer:
        'This is a request, not a quote. We’ll reply within one business day.',
    refLabel: 'Ref',
    timeFramePrefix: 'Time frame:',
    packagingPrefix: 'Packaging:',
    quantityPrefix: 'Quantity:',
    unitsSuffix: 'units',
    budgetOnPaper: 'Yearly Packaging Spend',
    specialistToAdvise: 'Specialist to advise',

    quantityLabel: 'Quantity',
    quantityPlaceholder: 'e.g. 500',
    quantityHelp: 'Quantities are in multiples of 100.',
    quantityError: 'Enter a quantity in multiples of 100.',
    notesLabel: 'Brief',
    notesPlaceholder: 'What you’re packaging and when you need it',
    timelineLabel: 'Time frame',
    timelinePlaceholder: 'e.g. Need quote by Sept 15 — Ship by mid-October',
    annualSpendLabel: 'Yearly Packaging Spend',
    shipToLabel: 'Ship to',
    addFilesLabel: 'Add files',
    additionalFilesLabel: 'Add files',
    filesDropTitle: 'Drop artwork, dielines or product photos',
    filesExpressDropTitle: 'Drop dielines, artwork, PDFs, or product photos',

    contactHeading: 'Your Information',
    contactDesc: '',
    firstName: 'First name',
    lastName: 'Last name',
    workEmail: 'Email',
    phone: 'Phone',
    company: 'Company',
    industry: 'Industry',
    companyOffice: 'Company Address',
    companyAddressHelp: 'No company? Use your name.',

    reviewPaperBadge: 'Quote request',
    requestSummary: 'Request summary',
    productsCountOne: '1 product',
    productsCountMany: '{n} products',
    noProductsCount: 'No products',
    requestAQuote: 'Request a quote',
    submitFootnote: 'We’ll follow up with a quote.',
    submitting: 'Submitting…',
    submitHelperContact:
        'Add your name and shipping location to submit request.',
    submitHelperExpress:
        'Add what you\'re packaging, a quantity, your name, and shipping location to submit request.',

    quoteRequested: 'Quote requested',
    quoteRequestedBody:
        'Thanks. We’ll follow up within one business day.',
    keepBrowsing: 'Keep browsing products',
    backToYourRequest: 'Back to Your Request',

    submitSuccessTitle: 'Request submitted',
    submitSuccessBody:
        'Thanks. A packaging specialist will follow up within one business day.',
    submitSuccessAction: 'Continue',
    submitErrorTitle: 'We couldn’t submit your request',
    submitErrorRetry: 'Try again',
    submitErrorClose: 'Close',
    /** Shown when the action throws rather than returning a validation error. */
    submitTransportError:
        'We couldn’t reach the server. Your answers are saved — please try again.',

    // Restore to 'Upload a document to pre-fill' to re-enable the banner.
    assistTitle: '',
    assistBody: '',
    uploadDocument: 'Upload a document',
    tryASample: 'Try a sample',
    assistDonePrefix: 'Pre-filled from',
    assistDoneSuffix: '— please review the fields below.',
    useDifferentDocument: 'Use a different document',
    assistReading: 'and pulling out the details…',

    browseProducts: 'Browse products',
    addProductsCta: 'Add products from the catalog',
    expandProductsCta: 'Add products to this request',
    removeLine: 'Remove',
    noProductsYet: 'No products on this request yet.',
    signIn: 'Sign in',

    leaveTitle: 'Save as draft?',
    leaveBody: 'Save to continue later, or discard.',
    leaveSave: 'Save draft',
    leaveDiscard: 'Discard',
    leaveCancel: 'Cancel',

    expressHeading: 'New request',

    expressPoolTitle: 'You already have products saved',
    expressPoolBodyOne:
        'You have 1 product in your request. Add it to this quote, or ask about your requirements on their own.',
    expressPoolBodyMany:
        'You have {n} products in your request. Add them to this quote, or ask about your requirements on their own.',
    expressPoolIncludeOne: 'Include my product',
    expressPoolIncludeMany: 'Include my {n} products',
    expressPoolRequirementsOnly: 'Requirements only',

    startBuilder: 'Continue your request',
    startExpress: 'Get a quote',
    entryExpress: 'Requirements Only Quote (Express)',
    entryProducts: 'Product Only Quote',
    entryServices: 'Service Only Quote',
    continueRequest: 'Continue your request',
    productsUpsellTitle: 'Products',
    productsUpsellSubtitle: '',
    yourRequestHeading: 'Your Request',
    yourRequestStub:
        'Start a new request or continue one in progress.',
    yourRequestSupporting:
        'Your added products. Select the ones you want quoted.',
    nothingAddedYet: 'Nothing added yet.',
    startYourRequest: 'Start your request',
    startYourRequestCount: 'Start your request ({n})',
    customizeLine: 'Customize',
    customizeUnavailable: 'Customization from Your Request is coming soon.',
    additionalNotesAction: 'Additional Notes',
    referenceImagesAction: 'Reference Images',
    saveNotes: 'Save',
    saveImages: 'Save',
    draftRequestsHeading: 'Draft requests',
    draftRequestsEmpty: 'No draft requests yet.',
    emptySelectHint: 'Select products to get started.',
    selectedCountOne: '1 product selected',
    selectedCountMany: '{n} products selected',
    selectedCountNone: 'No products selected',
} as const;

export const SERVICE_OPTIONS = [
    {id: 'design', label: 'Packaging Design'},
    {id: 'structural', label: 'Structural / Dieline Engineering'},
    {id: 'sourcing', label: 'Sourcing'},
    {id: 'fulfilment', label: 'Fulfilment'},
] as const;

export const INDUSTRY_OPTIONS = [
    'Food & Beverage',
    'Beauty & Personal Care',
    'Health & Wellness',
    'Cannabis',
    'Electronics',
    'Apparel & Accessories',
    'Home & Lifestyle',
    'Other',
] as const;
